<a href="https://colab.research.google.com/github/PierDiella/BigData_Rep/blob/main/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import random

In [3]:
df=pd.read_csv("student_prediction.csv")

df.head(10)

,STUDENTID,AGE,GENDER,HS_TYPE,SCHOLARSHIP,WORK,ACTIVITY,PARTNER,SALARY,TRANSPORT,...,PREP_STUDY,PREP_EXAM,NOTES,LISTENS,LIKES_DISCUSS,CLASSROOM,CUML_GPA,EXP_GPA,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1
5,STUDENT6,2,2,2,3,2,2,2,2,1,...,1,1,1,2,1,2,4,4,1,2
6,STUDENT7,1,2,2,4,2,2,2,1,1,...,1,1,3,3,3,3,4,4,1,5
7,STUDENT8,1,1,2,3,1,1,1,2,2,...,3,1,3,2,2,1,1,1,1,2
8,STUDENT9,2,1,3,3,2,1,1,1,1,...,1,1,3,2,2,2,4,3,1,5
9,STUDENT10,2,1,2,3,2,2,1,3,4,...,1,1,2,2,2,2,1,2,1,0

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64
 2   GENDER         145 non-null    int64
 3   HS_TYPE        145 non-null    int64
 4   SCHOLARSHIP    145 non-null    int64
 5   WORK           145 non-null    int64
 6   ACTIVITY       145 non-null    int64
 7   PARTNER        145 non-null    int64
 8   SALARY         145 non-null    int64
 9   TRANSPORT      145 non-null    int64
 10  LIVING         145 non-null    int64
 11  MOTHER_EDU     145 non-null    int64
 12  FATHER_EDU     145 non-null    int64
 13  #_SIBLINGS     145 non-null    int64
 14  KIDS           145 non-null    int64
 15  MOTHER_JOB     145 non-null    int64
 16  FATHER_JOB     145 non-null    int64
 17  STUDY_HRS      145 non-null    int64
 18  READ_FREQ      145 non-null    int64
 19  READ_FREQ_SCI  145 non-null    int64
 20  ATTEND_DEPT    145 non-null    int64
 21  IMPACT         145 non-null    int64
 22  ATTEND         145 non-null    int64
 23  PREP_STUDY     145 non-null    int64
 24  PREP_EXAM      145 non-null    int64
 25  NOTES          145 non-null    int64
 26  LISTENS        145 non-null    int64
 27  LIKES_DISCUSS  145 non-null    int64
 28  CLASSROOM      145 non-null    int64
 29  CUML_GPA       145 non-null    int64
 30  EXP_GPA        145 non-null    int64
 31  COURSE ID      145 non-null    int64
 32  GRADE          145 non-null    int64
dtypes: int64(32), object(1)
memory usage: 37.5+ KB
None

In [5]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)

[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.]
 [5.]
 [1.]
 [4.]
 [3.]]

In [8]:
print(X2.shape)
print(Y2.shape)

(145, 30)
(145, 1)

Squared Normalization

In [10]:
X = normalize(X2, norm='l2')

Y=Y2
print(X)
print(Y)

[[0.1796053  0.1796053  0.26940795 ... 0.1796053  0.08980265 0.08980265]
 [0.18490007 0.18490007 0.2773501  ... 0.18490007 0.18490007 0.2773501 ]
 [0.1933473  0.1933473  0.1933473  ... 0.09667365 0.1933473  0.1933473 ]
 ...
 [0.07881104 0.07881104 0.07881104 ... 0.07881104 0.31524416 0.23643312]
 [0.14948702 0.07474351 0.14948702 ... 0.07474351 0.37371755 0.22423053]
 [0.07254763 0.07254763 0.07254763 ... 0.07254763 0.36273813 0.2901905 ]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.]
 [5.]
 [1.]
 [4.]
 [3.]]

MinMax Regularization??????

In [45]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

Y1 = scaler.fit_transform(Y2)
Y = np.ravel(Y1)                                                                   # Appiattisce y
print(X)
print(Y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[ 4.28571429  4.28571429  4.28571429  4.28571429  4.28571429  8.57142857
 21.42857143  8.57142857 21.42857143  0.          8.57142857  0.
  0.          4.28571429  8.57142857  8.57142857  4.28571429  8.57142857
  8.57142857 12.85714286  4.28571429  4.28571429 12.85714286  4.28571429
  8.57142857 12.85714286  4.28571429  4.28571429 12.85714286 21.42857143
 21.42857143 12.85714286  4.28571429  8.57142857  8.57142857  4.28571429
  8.57142857  4.28571429  8.57142857  4.28571429  4.28571429  4.28571429
  4.28571429 17.14285714  4.28571429 12.85714286 21.42857143 12.85714286
  4.28571429  8.57142857  4.28571429 17.14285714  4.28571429 21.42857143
 12.85714286 12.85714286 21.42857143 17.14285714 12.85714286 21.42857143
  8.57142857 21.42857143 12.85714286 21.42857143 12.85714286  8.57142857
 21.42857143  4.28571429 21.42857143 21.42857143 30.         25.71428571
 25.71428571 25.71428571 30.         30.         17.14285714 30.
 17.14285714 12.85714286 17.14285714 12.85714286 30.         30.
 30.         17.14285714 21.42857143 25.71428571 25.71428571 25.71428571
 25.71428571 25.71428571 30.         17.14285714 25.71428571 21.42857143
 30.         25.71428571 30.         30.         25.71428571 30.
 30.         30.         12.85714286 30.         30.         25.71428571
 25.71428571 30.          8.57142857  8.57142857  8.57142857  4.28571429
  8.57142857  4.28571429  4.28571429  4.28571429  4.28571429  8.57142857
  4.28571429  0.          8.57142857  4.28571429 12.85714286  8.57142857
 12.85714286  4.28571429  0.         12.85714286  4.28571429 17.14285714
 12.85714286 12.85714286  4.28571429  8.57142857  0.          8.57142857
  0.          0.         21.42857143 21.42857143  4.28571429 17.14285714
 12.85714286]

# Multiple Linear Regression

In [46]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]

  cost = 0

  for i in range(m):   #for i = 1 : m
    X_i = X[i,:]
    f_Wb = np.dot(W, X_i) + b
    err_i = (f_Wb - Y[i])**2
    cost = cost + err_i
    total_cost=(1/(2*m))*cost
  return total_cost


W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])

b = 0

total_cost = compute_multiple_cost(X, Y, W, b)


print ('for b={} and W=1, total_cost={}'.format(b,total_cost))

for b=0 and W=1, total_cost=5804.333710610677

In [50]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]

  cost = 0

  for i in range(m):   #for i = 1 : m
    X_i = X[i,:]
    f_Wb = np.dot(W, X_i) + b
    err_i = (f_Wb - Y[i])**2
    cost = cost + err_i
    total_cost=(1/(2*m))*cost
  return total_cost


#W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
W = np.random.randn(30)
#b = 0
b = random.uniform(-5, 5)

total_cost = compute_multiple_cost(X, Y, W, b)


print ('for b={} and W={} randomic, total_cost={}'.format(b,W,total_cost))

for b=3.722329565881669 and W=[ 0.60179802 -1.02887422  0.3581594   0.1110346  -1.04221503  0.84284493
  1.35018386  0.56422595 -1.42668638 -0.90659771  0.43337883  0.09386674
  0.15288017  1.12850169 -0.55464729  0.85184517  1.11826197  0.29461368
 -0.18352197 -0.98525832 -0.1375693   0.12689606 -0.07721375 -0.20388419
  0.14685299  2.0862411   0.95461898  0.79283106 -1.64191364 -1.07125687] randomic, total_cost=248.14284464697295

In [51]:
def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0] #number of samples
  n = X.shape[1] #number of features

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): #for each sample
    X_i = X[i,:]
    f_xi = np.dot(W, X_i) + b; #prediction
    err_i = f_xi-Y[i]   #error=prediction-ground_truth
    for j in range(n): #for each features class
      x_ji = X[i, j]
      #print('f_xi = {}'.format(f_xi));
      #print('Y[i] = {}'.format(Y[i]));
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      #print('dj_dW[j] = {}'.format(dj_dW[j]))
    dj_db = dj_db + (1/m)*err_i;
  return dj_dW, dj_db


dj_dW, dj_db = compute_multiple_gradient(X, Y, W, b)

print ('for b={} and W={} randomic, \n dj_dW={} \n dj_db={}'.format(b,W,dj_dW,dj_db))

for b=3.722329565881669 and W=[ 0.60179802 -1.02887422  0.3581594   0.1110346  -1.04221503  0.84284493
  1.35018386  0.56422595 -1.42668638 -0.90659771  0.43337883  0.09386674
  0.15288017  1.12850169 -0.55464729  0.85184517  1.11826197  0.29461368
 -0.18352197 -0.98525832 -0.1375693   0.12689606 -0.07721375 -0.20388419
  0.14685299  2.0862411   0.95461898  0.79283106 -1.64191364 -1.07125687] randomic,
 dj_dW=[ 29.29812931 -26.11054692  17.2175975   15.79319182 -14.95828375
  38.35463016  51.63458019  14.89438531 -14.48405978  -5.79534875
   0.78938458   6.60938448  33.38097254   8.72405243  -2.99119277
  25.57542932  15.60889618  19.19845175  20.76468238   5.15290518
   9.63854309  28.72837683   1.20659933   1.46290703  19.01816152
  41.75011166  21.71269089  24.21342503 -11.30485904  -7.88171857]
 dj_db=3.4274902988560894

In [52]:
def multiple_gradient_descent (X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient):

  W = W_in
  b = b_in



  for itt in range(num_iters):

    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha * dj_dw
    b = b - alpha * dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
        print('Itteration {}:, (W,b) = ({}, {}),\n cost = {}'.format(itt, W, b,cost))
  return W, b, cost

W_in = W
b_in = b



alpha = 0.03
#alpha = 0.003282 #convergenza meno lenta §25
#alpha = 0.0001   #convergenza lenta
num_iters = 10000
multiple_gradient_descent(X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient)

Itteration 0:, (W,b) = ([-0.27714586 -0.24555781 -0.15836853 -0.36276115 -0.59346652 -0.30779397
 -0.19885355  0.11739439 -0.99216459 -0.73273725  0.4096973  -0.1044148
 -0.848549    0.86678011 -0.46491151  0.08458229  0.64999509 -0.28133987
 -0.80646245 -1.13984547 -0.42672559 -0.73495525 -0.11341173 -0.2477714
 -0.42369186  0.83373775  0.30323825  0.06642831 -1.30276787 -0.83480531], 3.6195048569159862),
 cost = 1190.5023247771703
Itteration 100:, (W,b) = ([-1.25584016e+123 -2.52491144e+123 -1.88950402e+123 -2.55689935e+123
 -2.72787823e+123 -2.47874141e+123 -2.36629244e+123 -5.96530635e+122
 -8.25637822e+122 -9.32451070e+122 -1.01559265e+123 -1.29707782e+123
 -1.83273485e+123 -3.37686531e+122 -1.32242693e+123 -1.79454321e+123
 -1.19556249e+123 -1.89507339e+123 -2.02604418e+123 -8.42299512e+122
 -3.91834951e+122 -9.56894516e+122 -6.37785095e+122 -3.32820040e+122
 -3.12007003e+123 -2.09475261e+123 -2.82909386e+123 -1.70203729e+123
 -2.19486483e+123 -2.37346441e+123], -3.943808846530306e+122),
 cost = 2.9634016903021536e+250

<ipython-input-50-375510085fe7>:11: RuntimeWarning: overflow encountered in double_scalars
  cost = cost + err_i
<ipython-input-50-375510085fe7>:10: RuntimeWarning: overflow encountered in double_scalars
  err_i = (f_Wb - Y[i])**2

Itteration 200:, (W,b) = ([-6.45042850e+246 -1.29688166e+247 -9.70514479e+246 -1.31331175e+247
 -1.40113241e+247 -1.27316714e+247 -1.21540946e+247 -3.06398722e+246
 -4.24076081e+246 -4.78939052e+246 -5.21643439e+246 -6.66223937e+246
 -9.41355875e+246 -1.73447457e+246 -6.79244113e+246 -9.21739326e+246
 -6.14082159e+246 -9.73375098e+246 -1.04064622e+247 -4.32634100e+246
 -2.01259954e+246 -4.91494049e+246 -3.27588437e+246 -1.70947859e+246
 -1.60257565e+247 -1.07593724e+247 -1.45312025e+247 -8.74225094e+246
 -1.12735833e+247 -1.21909324e+247], -2.0256763381641118e+246),
 cost = inf

<ipython-input-51-185308cdd9fa>:17: RuntimeWarning: invalid value encountered in double_scalars
  dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;

Itteration 300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 1900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 2900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 3900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 4900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 5900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 6900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 7900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 8900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9000:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9100:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9200:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9300:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9400:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9600:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9700:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9800:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan
Itteration 9900:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], nan),
 cost = nan

(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan]),
 nan,
 nan)