<a href="https://colab.research.google.com/github/PierDiella/BigData_Rep/blob/main/MultipleLinearRegression_Vs_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df=pd.read_csv("student_prediction.csv")

df.head(10)

,STUDENTID,AGE,GENDER,HS_TYPE,SCHOLARSHIP,WORK,ACTIVITY,PARTNER,SALARY,TRANSPORT,...,PREP_STUDY,PREP_EXAM,NOTES,LISTENS,LIKES_DISCUSS,CLASSROOM,CUML_GPA,EXP_GPA,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1
5,STUDENT6,2,2,2,3,2,2,2,2,1,...,1,1,1,2,1,2,4,4,1,2
6,STUDENT7,1,2,2,4,2,2,2,1,1,...,1,1,3,3,3,3,4,4,1,5
7,STUDENT8,1,1,2,3,1,1,1,2,2,...,3,1,3,2,2,1,1,1,1,2
8,STUDENT9,2,1,3,3,2,1,1,1,1,...,1,1,3,2,2,2,4,3,1,5
9,STUDENT10,2,1,2,3,2,2,1,3,4,...,1,1,2,2,2,2,1,2,1,0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64
 2   GENDER         145 non-null    int64
 3   HS_TYPE        145 non-null    int64
 4   SCHOLARSHIP    145 non-null    int64
 5   WORK           145 non-null    int64
 6   ACTIVITY       145 non-null    int64
 7   PARTNER        145 non-null    int64
 8   SALARY         145 non-null    int64
 9   TRANSPORT      145 non-null    int64
 10  LIVING         145 non-null    int64
 11  MOTHER_EDU     145 non-null    int64
 12  FATHER_EDU     145 non-null    int64
 13  #_SIBLINGS     145 non-null    int64
 14  KIDS           145 non-null    int64
 15  MOTHER_JOB     145 non-null    int64
 16  FATHER_JOB     145 non-null    int64
 17  STUDY_HRS      145 non-null    int64
 18  READ_FREQ      145 non-null    int64
 19  READ_FREQ_SCI  145 non-null    int64
 20  ATTEND_DEPT    145 non-null    int64
 21  IMPACT         145 non-null    int64
 22  ATTEND         145 non-null    int64
 23  PREP_STUDY     145 non-null    int64
 24  PREP_EXAM      145 non-null    int64
 25  NOTES          145 non-null    int64
 26  LISTENS        145 non-null    int64
 27  LIKES_DISCUSS  145 non-null    int64
 28  CLASSROOM      145 non-null    int64
 29  CUML_GPA       145 non-null    int64
 30  EXP_GPA        145 non-null    int64
 31  COURSE ID      145 non-null    int64
 32  GRADE          145 non-null    int64
dtypes: int64(32), object(1)
memory usage: 37.5+ KB
None

import data from DF: X matrix is made from each features (excluding STUDENT ID, COURSE ID), Y is GRADE. X is regularizated with squared L2 norm.

In [ ]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)

[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.]
 [5.]
 [1.]
 [4.]
 [3.]]

In [ ]:
print(X.shape)
print(Y.shape)

(145, 30)
(145, 1)

Squared normalization

In [ ]:
X = normalize(X2, norm='l2')

MinMaxRegularization

In [ ]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

Y = scaler.fit_transform(Y2)

print(X)
print(Y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[[ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [17.14285714]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 4.28571429]
 [17.14285714]
 [ 4.28571429]
 [21.42857143]
 [12.85714286]
 [12.85714286]
 [21.42857143]
 [17.14285714]
 [12.85714286]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [12.85714286]
 [21.42857143]
 [12.85714286]
 [ 8.57142857]
 [21.42857143]
 [ 4.28571429]
 [21.42857143]
 [21.42857143]
 [30.        ]
 [25.71428571]
 [25.71428571]
 [25.71428571]
 [30.        ]
 [30.        ]
 [17.14285714]
 [30.        ]
 [17.14285714]
 [12.85714286]
 [17.14285714]
 [12.85714286]
 [30.        ]
 [30.        ]
 [30.        ]
 [17.14285714]
 [21.42857143]
 [25.71428571]
 [25.71428571]
 [25.71428571]
 [25.71428571]
 [25.71428571]
 [30.        ]
 [17.14285714]
 [25.71428571]
 [21.42857143]
 [30.        ]
 [25.71428571]
 [30.        ]
 [30.        ]
 [25.71428571]
 [30.        ]
 [30.        ]
 [30.        ]
 [12.85714286]
 [30.        ]
 [30.        ]
 [25.71428571]
 [25.71428571]
 [30.        ]
 [ 8.57142857]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [ 4.28571429]
 [ 0.        ]
 [ 8.57142857]
 [ 4.28571429]
 [12.85714286]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 0.        ]
 [12.85714286]
 [ 4.28571429]
 [17.14285714]
 [12.85714286]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [21.42857143]
 [21.42857143]
 [ 4.28571429]
 [17.14285714]
 [12.85714286]]

# Multiple Linear Regression to predict Y from X

In [ ]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]

  cost = 0

  for i in range(m):   #for i = 1 : m
    X_i = X[i,:]
    f_Wb = np.dot(W, X_i) + b
    err_i = (f_Wb - Y[i])**2
    cost = cost + err_i
  total_cost=(1/(2*m))*cost
  return total_cost



W = np.random.randn(30)
b = 0

total_cost = compute_multiple_cost(X, Y, W, b)


print ('for b={} and W randomic, total_cost={}'.format(b,total_cost))

for b=0 and W randomic, total_cost=[238.46406101]

In [ ]:
def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0] #number of samples
  n = X.shape[1] #number of features

  dj_dw = np.zeros(n)
  dj_db = 0

  for i in range(m): #for each sample
    X_i = X[i,:]
    f_xi = np.dot(W, X_i) + b; #prediction
    err_i = f_xi-Y[i]   #error=prediction-ground_truth
    for j in range(n): #for each features class
      x_ji = X[i, j]
      dj_dw[j] = dj_dw[j] + (1/m)*x_ji*(err_i);
    dj_db = dj_db + (1/m)*(err_i);
  return dj_dw, dj_db

W = np.random.randn(30)
b = 0

dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
print(dj_dw, dj_db)

[-1.73762130e+01 -9.42110684e+01 -3.98595889e+01 -4.36089800e+01
 -1.08119229e+02 -8.76343175e+01 -5.36784439e+01 -1.95593987e+00
 -1.06154427e+01 -4.61760608e+00 -1.23214073e+01 -3.09124002e+01
 -5.93652787e+01 -1.60797336e+00 -1.14718305e+01 -3.53861287e+01
 -2.62184906e+01 -3.64534025e+01 -2.86081350e+01  5.37364664e+00
  1.51728188e+00 -1.71983198e+01 -8.64167187e-02 -5.95587400e+00
 -6.20279443e+01 -4.03915770e+01 -5.24376374e+01 -3.58786773e+01
 -4.52473567e+01 -4.17684901e+01] [-8.03573086]

In [ ]:
def multiple_gradient_descent (X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient):

  b = b_in
  W = W_in



  for itt in range(num_iters):

    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha * dj_dw
    b = b - alpha * dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
        print('Itteration {}:, (W,b) = ({}, {}), cost = {}'.format(itt, W, b,cost))
  return W, b, cost




W_in = np.random.randn(30)
b_in = 0
alpha = 0.01
num_iters = 10000
multiple_gradient_descent(X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient)

Itteration 0:, (W,b) = ([ 1.02635441  1.09762332 -0.26722539  1.2953934   0.70895802  1.829943
  1.47769105  1.09007928 -0.12137194  0.1519879   1.03525957  1.2403795
  1.8464751  -0.65608382  0.49947922  2.69530585  0.4392198   1.16866053
  1.62385261  0.57177743 -1.33384272 -0.51003805 -0.43159895  0.65046701
  3.20119007  2.14670283  2.95179307 -0.06752975  2.31489515  2.75497599], [0.30397851]), cost = [12610.00386319]
Itteration 100:, (W,b) = ([3.64271384e+70 7.32380611e+70 5.48073128e+70 7.41659085e+70
 7.91253546e+70 7.18988446e+70 6.86371282e+70 1.73030810e+70
 2.39486076e+70 2.70468530e+70 2.94584736e+70 3.76232859e+70
 5.31606555e+70 9.79499971e+69 3.83585669e+70 5.20528613e+70
 3.46787129e+70 5.49688589e+70 5.87678225e+70 2.44318998e+70
 1.13656391e+70 2.77558642e+70 1.84997157e+70 9.65384133e+69
 9.05013443e+70 6.07607923e+70 8.20612343e+70 4.93696171e+70
 6.36646665e+70 6.88451598e+70], [1.14394869e+70]), cost = [2.49328487e+145]
Itteration 200:, (W,b) = ([1.63000775e+141 3.27718873e+141 2.45246672e+141 3.31870719e+141
 3.54062787e+141 3.21726271e+141 3.07131046e+141 7.74262196e+140
 1.07163005e+141 1.21026745e+141 1.31818041e+141 1.68353185e+141
 2.37878363e+141 4.38297549e+140 1.71643352e+141 2.32921309e+141
 1.55177083e+141 2.45969544e+141 2.62968794e+141 1.09325596e+141
 5.08579060e+140 1.24199363e+141 8.27808094e+140 4.31981125e+140
 4.04967009e+141 2.71886750e+141 3.67199989e+141 2.20914577e+141
 2.84880736e+141 3.08061926e+141], [5.11883534e+140]), cost = [4.99230523e+286]

<ipython-input-50-340a1cfd6172>:11: RuntimeWarning: overflow encountered in add
  cost = cost + err_i
<ipython-input-50-340a1cfd6172>:10: RuntimeWarning: overflow encountered in square
  err_i = (f_Wb - Y[i])**2

Itteration 300:, (W,b) = ([7.29380730e+211 1.46644597e+212 1.09740703e+212 1.48502427e+212
 1.58432727e+212 1.43963084e+212 1.37432148e+212 3.46459656e+211
 4.79523060e+211 5.41559239e+211 5.89847127e+211 7.53331194e+211
 1.06443601e+212 1.96125316e+211 7.68053729e+211 1.04225464e+212
 6.94371999e+211 1.10064167e+212 1.17670833e+212 4.89200021e+211
 2.27574234e+211 5.55755773e+211 3.70419877e+211 1.93298901e+211
 1.81210876e+212 1.21661357e+212 1.64311240e+212 9.88528028e+211
 1.27475786e+212 1.37848689e+212], [2.29052889e+211]), cost = [inf]
Itteration 400:, (W,b) = ([3.26376514e+282 6.56191623e+282 4.91057504e+282 6.64504864e+282
 7.08940051e+282 6.44192634e+282 6.14968608e+282 1.55030549e+282
 2.14572525e+282 2.42331898e+282 2.63939313e+282 3.37093646e+282
 4.76303937e+282 8.77603347e+281 3.43681549e+282 4.66378424e+282
 3.10711132e+282 4.92504910e+282 5.26542514e+282 2.18902681e+282
 1.01832804e+282 2.48684431e+282 1.65752046e+282 8.64955969e+281
 8.10865595e+282 5.44398941e+282 7.35244676e+282 4.42337340e+282
 5.70416805e+282 6.16832511e+282], [1.02494459e+282]), cost = [inf]

<ipython-input-51-364182d7c54a>:15: RuntimeWarning: overflow encountered in add
  dj_dw[j] = dj_dw[j] + (1/m)*x_ji*(err_i);
<ipython-input-51-364182d7c54a>:15: RuntimeWarning: invalid value encountered in multiply
  dj_dw[j] = dj_dw[j] + (1/m)*x_ji*(err_i);

Itteration 500:, (W,b) = ([nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan], [nan]), cost = [nan]

KeyboardInterrupt: ignored

# Logistic Regression

In [ ]:
def sig(x):
 return 1/(1 + np.exp(-x))

In [ ]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, Y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))

for b=0, total_cost=[nan]

<ipython-input-61-78d490681f06>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-61-78d490681f06>:9: RuntimeWarning: invalid value encountered in add
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-61-78d490681f06>:9: RuntimeWarning: invalid value encountered in multiply
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)

In [ ]:
def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, Y, W, b)
print(dj_dW, dj_db)

[ -7.4677336  -20.29691509 -13.09076492 -16.98700124 -20.42707565
 -16.25783186 -14.9400779   -3.2660527   -4.24122949  -6.3505431
  -6.96209884  -9.17938823 -13.03908604  -2.39826175  -8.57895212
 -11.65870575  -7.83320229 -13.52216364 -13.21176343  -3.60562185
  -1.39861171  -5.17354204  -4.27806139  -2.39404215 -20.82704211
 -14.52865984 -19.32440299 -11.6634463  -16.19463563 -16.62282156] [-2.65941079]

In [ ]:
def multiple_gradient_descent(X, Y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, Y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}), cost = {}'.format(itt, W, b, cost))

  return W, b, cost


b_in = 1

alpha = 0.00002
num_iters = 500

multiple_gradient_descent(X, Y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)

Iteration 0: (w,b) = ([ 0.0598346  -1.1674848  -1.87494178 -0.6102124  -1.7932182  -0.18500775
 -0.42386323  0.66514425 -0.89029809 -0.56164582  0.18469466  0.13168987
  0.61896375 -0.92001029 -0.55386264  1.55930108 -0.37282174 -0.33042028
  0.12627232 -0.00199474 -1.77258728 -1.52733385 -0.98095918  0.47618472
  0.93502866  0.67204586  0.94571594 -1.55020971  0.76259321  1.09346559], [1.00005982]), cost = [26.46073362]
Iteration 100: (w,b) = ([ 0.07720129 -1.12359817 -1.84519437 -0.5721139  -1.74904669 -0.15016117
 -0.39033482  0.67266559 -0.87972729 -0.54705755  0.20076887  0.15196685
  0.64633021 -0.91415499 -0.53390999  1.58464245 -0.3558322  -0.29984992
  0.15609812  0.00700067 -1.76862827 -1.51473021 -0.9708077   0.48151244
  0.98091932  0.70403487  0.9883862  -1.52360566  0.79805017  1.13029525], [1.00598128]), cost = [20.82762023]
Iteration 200: (w,b) = ([ 0.09408687 -1.08041645 -1.81598344 -0.53467505 -1.70555314 -0.11586405
 -0.35741926  0.67994825 -0.86923386 -0.53263212  0.21653834  0.17193892
  0.67298169 -0.90844638 -0.51427202  1.60929176 -0.33918817 -0.26997004
  0.18519318  0.01594864 -1.76469546 -1.50236683 -0.96070176  0.48669161
  1.0260036   0.73533046  1.03019432 -1.49748116  0.83283524  1.16638027], [1.01179198]), cost = [15.4045576]

<ipython-input-55-78d490681f06>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)

Iteration 300: (w,b) = ([ 0.11046299 -1.03796816 -1.7873178  -0.49782611 -1.66271275 -0.08200298
 -0.32491911  0.68703643 -0.85886647 -0.5184616   0.23193686  0.19157504
  0.69916423 -0.90285666 -0.49495504  1.63338391 -0.32277138 -0.24071432
  0.21369662  0.02481218 -1.76076641 -1.49020481 -0.95072843  0.49174718
  1.07029615  0.76594415  1.07127196 -1.47168734  0.86706077  1.20180798], [1.01749872]), cost = [-inf]
Iteration 400: (w,b) = ([ 0.12627735 -0.99656758 -1.75927202 -0.46165249 -1.62070803 -0.04895742
 -0.29282639  0.69385151 -0.84870858 -0.50459451  0.24701446  0.210795
  0.72479362 -0.89754371 -0.47602051  1.6568785  -0.30662687 -0.21203161
  0.24163476  0.03358716 -1.75689838 -1.47823649 -0.9410494   0.49661634
  1.11368307  0.79585214  1.11146296 -1.4462777   0.90044629  1.23637963], [1.02308603]), cost = [-inf]

<ipython-input-55-78d490681f06>:9: RuntimeWarning: invalid value encountered in multiply
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)

(array([ 0.14154661, -0.95658059, -1.73217548, -0.42661   , -1.57989282,
        -0.01716235, -0.26175121,  0.70029801, -0.83897302, -0.49118172,
         0.26164707,  0.2293745 ,  0.74965998, -0.89243014, -0.45774163,
         1.67956161, -0.29105057, -0.18421579,  0.26863102,  0.04192258,
        -1.75317856, -1.46671605, -0.93161107,  0.50131421,  1.15554814,
         0.82488845,  1.15028322, -1.42155194,  0.93277272,  1.26979689]),
 array([1.02849051]),
 array([nan]))